create extension if not exists pgcrypto;

alter table public.audit_events
add column if not exists immutable_sequence bigint generated by default as identity,
add column if not exists prev_event_hash text,
add column if not exists event_hash text,
add column if not exists integrity_version text not null default 'sha256-chain-v1';

create unique index if not exists idx_audit_events_immutable_sequence
  on public.audit_events(immutable_sequence);

create index if not exists idx_audit_events_action
  on public.audit_events(action);

create index if not exists idx_audit_events_entity
  on public.audit_events(entity_type, entity_id);

update public.audit_events
set event_hash = encode(
  extensions.digest(
    convert_to(concat_ws('|', id::text, coalesce(actor_user_id::text, ''), coalesce(target_user_id::text, ''), action, entity_type, coalesce(entity_id, ''), coalesce(from_status, ''), coalesce(to_status, ''), coalesce(reason, ''), metadata::text, created_at::text), 'UTF8'),
    'sha256'
  ),
  'hex'
)
where event_hash is null;

create or replace function app_private.set_audit_event_hash()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  previous_hash text;
begin
  select ae.event_hash
  into previous_hash
  from public.audit_events ae
  where ae.event_hash is not null
  order by ae.immutable_sequence desc
  limit 1;

  new.prev_event_hash := previous_hash;
  new.event_hash := encode(
    extensions.digest(
      convert_to(concat_ws('|', new.id::text, coalesce(new.actor_user_id::text, ''), coalesce(new.target_user_id::text, ''), new.action, new.entity_type, coalesce(new.entity_id, ''), coalesce(new.from_status, ''), coalesce(new.to_status, ''), coalesce(new.reason, ''), new.metadata::text, new.created_at::text, coalesce(previous_hash, '')), 'UTF8'),
      'sha256'
    ),
    'hex'
  );
  new.integrity_version := 'sha256-chain-v1';
  return new;
end;
$$;

create or replace function app_private.prevent_audit_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'audit_events are immutable and cannot be updated or deleted';
end;
$$;

drop trigger if exists trg_set_audit_event_hash on public.audit_events;
create trigger trg_set_audit_event_hash
before insert on public.audit_events
for each row execute function app_private.set_audit_event_hash();

drop trigger if exists trg_prevent_audit_event_update on public.audit_events;
create trigger trg_prevent_audit_event_update
before update on public.audit_events
for each row execute function app_private.prevent_audit_event_mutation();

drop trigger if exists trg_prevent_audit_event_delete on public.audit_events;
create trigger trg_prevent_audit_event_delete
before delete on public.audit_events
for each row execute function app_private.prevent_audit_event_mutation();

create table if not exists public.audit_export_requests (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'requested'
    check (status in ('requested', 'generated', 'verified', 'expired')),
  owner_role text not null default 'HR_ADMIN'
    check (owner_role in ('HR_ADMIN', 'SYSTEM')),
  next_action text,
  filters jsonb not null default '{}'::jsonb,
  row_count integer not null default 0,
  export_format text not null default 'csv'
    check (export_format in ('csv', 'json')),
  export_payload text,
  payload_hash text,
  generated_at timestamptz,
  verified_at timestamptz,
  expired_at timestamptz,
  requested_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_audit_export_requests_status
  on public.audit_export_requests(status);

create index if not exists idx_audit_export_requests_requested_by
  on public.audit_export_requests(requested_by);

insert into public.permissions (code, description)
values
  ('compliance.audit.read', 'Read immutable audit log'),
  ('compliance.audit.export', 'Export immutable audit log'),
  ('compliance.audit.verify', 'Verify audit log hash chain')
on conflict (code) do update set description = excluded.description;

insert into public.role_permissions (role_code, permission_code)
values
  ('HR_ADMIN', 'compliance.audit.read'),
  ('HR_ADMIN', 'compliance.audit.export'),
  ('HR_ADMIN', 'compliance.audit.verify'),
  ('HRBP', 'compliance.audit.read')
on conflict do nothing;

alter table public.audit_export_requests enable row level security;

grant select on public.audit_events to authenticated;
grant select, insert, update on public.audit_export_requests to authenticated;
grant all on public.audit_export_requests to service_role;

drop policy if exists "compliance can read audit events" on public.audit_events;
create policy "compliance can read audit events"
on public.audit_events for select
to authenticated
using (
  (select app_private.current_user_has_role('HR_ADMIN'))
  or (select app_private.current_user_has_role('HRBP'))
  or actor_user_id = (select auth.uid())
  or target_user_id = (select auth.uid())
);

drop policy if exists "compliance can read audit export requests" on public.audit_export_requests;
create policy "compliance can read audit export requests"
on public.audit_export_requests for select
to authenticated
using (
  requested_by = (select auth.uid())
  or (select app_private.current_user_has_role('HR_ADMIN'))
);

drop policy if exists "hr admin can write audit export requests" on public.audit_export_requests;
create policy "hr admin can write audit export requests"
on public.audit_export_requests for all
to authenticated
using ((select app_private.current_user_has_role('HR_ADMIN')))
with check ((select app_private.current_user_has_role('HR_ADMIN')));

insert into public.audit_events (
  actor_user_id,
  action,
  entity_type,
  entity_id,
  to_status,
  metadata
)
values (
  null,
  'compliance.audit_immutable_enabled',
  'audit_events',
  'audit_events',
  'immutable',
  '{"owner":"SYSTEM","nextAction":null,"integrityVersion":"sha256-chain-v1"}'::jsonb
);
